#!/bin/bash
# Usage: cat files | tovim
# Opens a list of files in vim
# Author: Matt Carter <m@ttcarter.com>

DIR=$(readlink -f "$0")
DIR=`dirname "$DIR"`

cat /dev/stdin | xargs "$DIR/tovim.bin" vim
